/**
 * Warehouse Management System API
 * API for managing items, orders, locations, and customers in a warehouse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CustomerUpdate { 
    /**
     * Name of the customer.
     */
    firstName: string;
    lastName: string;
    passportNo?: string;
    phoneNo?: string;
    /**
     * Email address of the customer.
     */
    email: string;
    /**
     * Address of the customer.
     */
    address: string;
}