/**
 * Warehouse Management System API
 * API for managing items, orders, locations, and customers in a warehouse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item { 
    /**
     * Unique identifier for the item.
     */
    id: string;
    /**
     * Name of the item.
     */
    name: string;
    /**
     * Number of items available.
     */
    quantity: number;
    description?: string;
    unitOfMeasure: string;
    /**
     * ID of the storage location.
     */
    locationId: string;
    /**
     * Price of the item.
     */
    price: number;
}