/**
 * Warehouse Management System API
 * API for managing items, orders, locations, and customers in a warehouse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Location { 
    /**
     * Unique identifier for the location.
     */
    id?: string;
    /**
     * Name of the storage location.
     */
    name?: string;
    /**
     * Maximum capacity of the location.
     */
    capacity?: number;
    /**
     * Current capacity of the location.
     */
    currentCapacity?: number;
}